<?php

namespace Database\Seeders;

use App\Models\Termekek;
use Illuminate\Database\Seeder;

class TermekekSeeder extends Seeder
{
    public function run(): void
    {
        Termekek::insert([

            [
                'nev' => 'Nike Air Max 90',
                'kategoria_id' => 1,
                'marka_id' => 1,
                'nem' => 'ferfi',
                'anyag' => 'textil',
                'kepUrl' => 'NikeAirmax90.jpg',
                'ar' => 54990,
                'elerheto' => true,
                'leiras' => 'Ikonikus Air Max modell kényelmes párnázással és sportos megjelenéssel.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Nike Revolution 6',
                'kategoria_id' => 2,
                'marka_id' => 1,
                'nem' => 'no',
                'anyag' => 'mesh',
                'kepUrl' => 'NikeRevolution6.jpg',
                'ar' => 21990,
                'elerheto' => true,
                'leiras' => 'Könnyű futócipő légáteresztő felsőrésszel és puha hab talppal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Nike Court Vision Low',
                'kategoria_id' => 3,
                'marka_id' => 1,
                'nem' => 'unisex',
                'anyag' => 'bőr',
                'kepUrl' => 'NikeCourtVision.jpg',
                'ar' => 28990,
                'elerheto' => true,
                'leiras' => 'Retro kosárlabda stílus modern utcai viselethez.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Adidas Superstar',
                'kategoria_id' => 4,
                'marka_id' => 2,
                'nem' => 'unisex',
                'anyag' => 'bőr',
                'kepUrl' => 'AdidasSuperstar.jpg',
                'ar' => 39990,
                'elerheto' => true,
                'leiras' => 'Legendás kagylóorrú sneaker időtálló dizájnnal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Adidas Ultraboost 22',
                'kategoria_id' => 5,
                'marka_id' => 2,
                'nem' => 'ferfi',
                'anyag' => 'primeknit',
                'kepUrl' => 'AdidasUlrtaboots22.jpg',
                'ar' => 69990,
                'elerheto' => true,
                'leiras' => 'Prémium futócipő Boost technológiával maximális kényelemért.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Adidas Harden Vol. 7',
                'kategoria_id' => 6,
                'marka_id' => 2,
                'nem' => 'ferfi',
                'anyag' => 'textil',
                'kepUrl' => 'AdidasHardenVol7.jpg',
                'ar' => 64990,
                'elerheto' => true,
                'leiras' => 'Kosárlabda cipő kiváló stabilitással és tapadással.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Puma RS-X',
                'kategoria_id' => 7,
                'marka_id' => 3,
                'nem' => 'unisex',
                'anyag' => 'textil',
                'kepUrl' => 'PumaRSX.jpg',
                'ar' => 42990,
                'elerheto' => true,
                'leiras' => 'Modern utcai sneaker merész dizájnnal és kényelmes talppal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Puma Suede Classic',
                'kategoria_id' => 8,
                'marka_id' => 3,
                'nem' => 'ferfi',
                'anyag' => 'velúr',
                'kepUrl' => 'PumaSuedeClassic.jpg',
                'ar' => 29990,
                'elerheto' => true,
                'leiras' => 'Klasszikus velúr sneaker letisztult megjelenéssel.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Jordan One Take 4',
                'kategoria_id' => 9,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'textil',
                'kepUrl' => 'JordanOneTake4.jpg',
                'ar' => 45990,
                'elerheto' => true,
                'leiras' => 'Dinamikus kosárlabda cipő kiváló párnázással.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Reebok Classic Leather',
                'kategoria_id' => 10,
                'marka_id' => 5,
                'nem' => 'unisex',
                'anyag' => 'bőr',
                'kepUrl' => 'ReebokClassicLeather.jpg',
                'ar' => 27990,
                'elerheto' => true,
                'leiras' => 'Minimalista klasszikus sneaker kényelmes kialakítással.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Reebok Question Mid',
                'kategoria_id' => 11,
                'marka_id' => 5,
                'nem' => 'ferfi',
                'anyag' => 'bőr',
                'kepUrl' => 'ReebokQuestionMid.jpg',
                'ar' => 59990,
                'elerheto' => true,
                'leiras' => 'Kosárlabda legenda ihlette prémium modell.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Vans Old Skool',
                'kategoria_id' => 12,
                'marka_id' => 6,
                'nem' => 'unisex',
                'anyag' => 'vászon',
                'kepUrl' => 'VansOldSkool.jpg',
                'ar' => 26990,
                'elerheto' => true,
                'leiras' => 'Skate stílus ikonikus oldalcsíkkal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'New Balance 574',
                'kategoria_id' => 13,
                'marka_id' => 7,
                'nem' => 'unisex',
                'anyag' => 'velúr',
                'kepUrl' => 'NewBalance574.jpg',
                'ar' => 37990,
                'elerheto' => true,
                'leiras' => 'Klasszikus NB modell kényelmes középtalppal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Converse Chuck Taylor All Star',
                'kategoria_id' => 14,
                'marka_id' => 8,
                'nem' => 'unisex',
                'anyag' => 'vászon',
                'kepUrl' => 'ConverseAllStar.jpg',
                'ar' => 24990,
                'elerheto' => true,
                'leiras' => 'Időtálló tornacipő legendás dizájnnal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'nev' => 'Nike SB Dunk Low',
                'kategoria_id' => 15,
                'marka_id' => 1,
                'nem' => 'unisex',
                'anyag' => 'bőr',
                'kepUrl' => 'NikeSBDunkLow.jpg',
                'ar' => 49990,
                'elerheto' => true,
                'leiras' => 'Skateboarding ihlette ikonikus sneaker.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Adidas Originals Gazelle',
                'kategoria_id' => 16,
                'marka_id' => 2,
                'nem' => 'unisex',
                'anyag' => 'velúr',
                'kepUrl' => 'AdidasGazelle.jpg',
                'ar' => 35990,
                'elerheto' => true,
                'leiras' => 'Retro stílusú Adidas sneaker velúr felsőrésszel.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Air Jordan 1 Mid',
                'kategoria_id' => 22,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'bőr',
                'kepUrl' => 'AirJordan1Mid.jpg',
                'ar' => 57990,
                'elerheto' => true,
                'leiras' => 'Kosárlabda ikon modern streetwear változatban.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Adidas Forum Low',
                'kategoria_id' => 23,
                'marka_id' => 2,
                'nem' => 'unisex',
                'anyag' => 'bőr',
                'kepUrl' => 'AdidasForumLow.jpg',
                'ar' => 41990,
                'elerheto' => true,
                'leiras' => 'Retro kosárlabda cipő modern megjelenéssel.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Balenciaga Triple S',
                'kategoria_id' => 17,
                'marka_id' => 11,
                'nem' => 'ferfi',
                'anyag' => 'bőr',
                'kepUrl' => 'BaleciagaTripleS.jpg',
                'ar' => 349990,
                'elerheto' => true,
                'leiras' => 'Luxus designer sneaker masszív talppal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Alexander McQueen Oversized Sneaker',
                'kategoria_id' => 18,
                'marka_id' => 12,
                'nem' => 'no',
                'anyag' => 'bőr',
                'kepUrl' => 'AlexanderMcQueen.jpg',
                'ar' => 229990,
                'elerheto' => true,
                'leiras' => 'Elegáns prémium sneaker minimalista stílussal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Gucci Rhyton',
                'kategoria_id' => 19,
                'marka_id' => 13,
                'nem' => 'unisex',
                'anyag' => 'bőr',
                'kepUrl' => 'GucciRhyton.jpg',
                'ar' => 329990,
                'elerheto' => true,
                'leiras' => 'Luxus streetwear sneaker egyedi dizájnnal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Off-White Odsy-1000',
                'kategoria_id' => 20,
                'marka_id' => 14,
                'nem' => 'ferfi',
                'anyag' => 'textil',
                'kepUrl' => 'Odsy1000.jpg',
                'ar' => 279990,
                'elerheto' => true,
                'leiras' => 'Modern designer sneaker futurisztikus megjelenéssel.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Maison Margiela Replica',
                'kategoria_id' => 21,
                'marka_id' => 15,
                'nem' => 'gyerek',
                'anyag' => 'bőr',
                'kepUrl' => 'MaisonMargelaReplica.jpg',
                'ar' => 189990,
                'elerheto' => true,
                'leiras' => 'Prémium minimalista sneaker luxus kivitelben.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Veja V-10',
                'kategoria_id' => 24,
                'marka_id' => 16,
                'nem' => 'gyerek',
                'anyag' => 'textil',
                'kepUrl' => 'VejaV10.jpg',
                'ar' => 59990,
                'elerheto' => true,
                'leiras' => 'Fenntartható anyagokból készült modern sneaker.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Allbirds Wool Runner',
                'kategoria_id' => 25,
                'marka_id' => 17,
                'nem' => 'gyerek',
                'anyag' => 'gyapjú',
                'kepUrl' => 'AllbirdWoolRunner.jpg',
                'ar' => 45990,
                'elerheto' => true,
                'leiras' => 'Kényelmes gyapjú sneaker mindennapi viselethez.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Cariuma OCA Low',
                'kategoria_id' => 26,
                'marka_id' => 18,
                'nem' => 'no',
                'anyag' => 'vászon',
                'kepUrl' => 'CariumaOCA.jpg',
                'ar' => 32990,
                'elerheto' => true,
                'leiras' => 'Könnyű vászon sneaker fenntartható gyártással.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Adidas x Parley Ultraboost',
                'kategoria_id' => 27,
                'marka_id' => 2,
                'nem' => 'unisex',
                'anyag' => 'újrahasznosított textil',
                'kepUrl' => 'AdidasXParley.jpg',
                'ar' => 72990,
                'elerheto' => true,
                'leiras' => 'Újrahasznosított anyagokból készült prémium futócipő.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nev' => 'Nike Space Hippie 04',
                'kategoria_id' => 28,
                'marka_id' => 1,
                'nem' => 'ferfi',
                'anyag' => 'újrahasznosított textil',
                'kepUrl' => 'NikeSpaceHippie04.jpg',
                'ar' => 48990,
                'elerheto' => true,
                'leiras' => 'Környezetbarát sneaker modern technológiával.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 4 Retro Black Cat (2025)',
                'kategoria_id' => 29,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'bor/szintetikus',
                'kepUrl' => 'Jordan4RetroBlackCat2025.jpg',
                'ar' => 185000,
                'elerheto' => true,
                'leiras' => 'Ikonikus, teljesen fekete nubuk borítású klasszikus kosárlabda cipő.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Nike Air Force 1 Low 07 White / Lanvin Black White Rope',
                'kategoria_id' => 30,
                'marka_id' => 1,
                'nem' => 'unisex',
                'anyag' => 'bor',
                'kepUrl' => 'AF1LanvinRope.jpg',
                'ar' => 64990,
                'elerheto' => true,
                'leiras' => 'Klasszikus sneaker exkluzív Lanvin stílusú vastag fűzőkkel modernizálva.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Nike Air Force 1 Low Supreme White',
                'kategoria_id' => 31,
                'marka_id' => 1,
                'nem' => 'unisex',
                'anyag' => 'bor',
                'kepUrl' => 'AF1SupremeWhite.jpg',
                'ar' => 75000,
                'elerheto' => true,
                'leiras' => 'Letisztult fehér felsőrész diszkrét piros Supreme logóval a sarokrészen.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Nike Air Force 1 Low 07 Black / White Denim Tears Custom',
                'kategoria_id' => 32,
                'marka_id' => 1,
                'nem' => 'ferfi',
                'anyag' => 'bor',
                'kepUrl' => 'AF1DenimTears.jpg',
                'ar' => 89990,
                'elerheto' => true,
                'leiras' => 'Egyedi megjelenésű, Denim Tears inspirálta különleges grafikájú sneaker.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Nike Air Force 1 Low 07 Black / Rose Rope Laces',
                'kategoria_id' => 33,
                'marka_id' => 1,
                'nem' => 'no',
                'anyag' => 'bor',
                'kepUrl' => 'AF1RoseRope.jpg',
                'ar' => 62990,
                'elerheto' => true,
                'leiras' => 'Elegáns fekete alap rózsaszín vastag kötélfűzőkkel kombinálva.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 4 Retro Fear (2024)',
                'kategoria_id' => 34,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'bor/szintetikus',
                'kepUrl' => 'Jordan4Fear.jpg',
                'ar' => 95000,
                'elerheto' => true,
                'leiras' => 'Sötét árnyalatú, félelmetes stílust sugárzó prémium kosárlabda cipő.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 4 Retro Frozen Moments',
                'kategoria_id' => 35,
                'marka_id' => 4,
                'nem' => 'no',
                'anyag' => 'bor/velur',
                'kepUrl' => 'Jordan4FrozenMoments.jpg',
                'ar' => 115000,
                'elerheto' => true,
                'leiras' => 'Fémes részletekkel és szürke nubukkal készült különleges női kiadás.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 4 Retro Metallic Gold',
                'kategoria_id' => 36,
                'marka_id' => 4,
                'nem' => 'no',
                'anyag' => 'bor',
                'kepUrl' => 'Jordan4MetallicGold.jpg',
                'ar' => 92000,
                'elerheto' => true,
                'leiras' => 'Tiszta fehér alap arany kiegészítőkkel a prémium megjelenésért.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 4 Retro SE Paris Olympics Wet Cement',
                'kategoria_id' => 37,
                'marka_id' => 4,
                'nem' => 'gyerek',
                'anyag' => 'nubuk/velúr',
                'kepUrl' => 'Jordan4Paris.jpg',
                'ar' => 110000,
                'elerheto' => true,
                'leiras' => 'A párizsi olimpia tiszteletére kiadott texturált szürke különlegesség.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 4 Retro Infrared',
                'kategoria_id' => 38,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'szintetikus/bor',
                'kepUrl' => 'Jordan4Infrared.jpg',
                'ar' => 120000,
                'elerheto' => true,
                'leiras' => 'Szürke és fekete színek élénk infravörös részletekkel feldobva.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 4 Retro Red Thunder',
                'kategoria_id' => 39,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'nubuk',
                'kepUrl' => 'Jordan4RedThunder.jpg',
                'ar' => 145000,
                'elerheto' => true,
                'leiras' => 'Fekete nubuk alap, kontrasztos piros betétekkel a dinamikus megjelenésért.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 4 Retro University Blue',
                'kategoria_id' => 40,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'velúr',
                'kepUrl' => 'Jordan4UniBlue.jpg',
                'ar' => 175000,
                'elerheto' => true,
                'leiras' => 'Az UNC egyetem színeiben pompázó, prémium velúr borítású modell.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Low SE Concord',
                'kategoria_id' => 41,
                'marka_id' => 4,
                'nem' => 'unisex',
                'anyag' => 'lakkbor',
                'kepUrl' => 'Jordan1LowConcord.jpg',
                'ar' => 52000,
                'elerheto' => true,
                'leiras' => 'A klasszikus AJ11 Concord színvilág alacsony szárú AJ1 változata.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Retro High OG Rebellionaire',
                'kategoria_id' => 42,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'bor',
                'kepUrl' => 'Jordan1Rebellionaire.jpg',
                'ar' => 98000,
                'elerheto' => true,
                'leiras' => 'Teljes felületén graffitivel ellátott modell, a "Banned" kampány emlékezetére.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Retro High OG Lucky Green',
                'kategoria_id' => 43,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'bor',
                'kepUrl' => 'Jordan1LuckyGreen.jpg',
                'ar' => 78000,
                'elerheto' => true,
                'leiras' => 'Zöld és fekete színek kombinációja a klasszikus Celtics stílusban.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Retro High OG Chicago Lost and Found',
                'kategoria_id' => 44,
                'marka_id' => 4,
                'nem' => 'unisex',
                'anyag' => 'bor',
                'kepUrl' => 'Jordan1LostAndFound.jpg',
                'ar' => 165000,
                'elerheto' => true,
                'leiras' => 'Visszatérés a gyökerekhez: az eredeti Chicago színállás antikolt hatással.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Retro High OG Spider-Man Across the Spider-Verse',
                'kategoria_id' => 45,
                'marka_id' => 4,
                'nem' => 'gyerek',
                'anyag' => 'bor/szintetikus',
                'kepUrl' => 'Jordan1Spiderverse.jpg',
                'ar' => 85000,
                'elerheto' => true,
                'leiras' => 'A Pókember animációs film inspirálta multiverzum stílusú cipő.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Retro High OG Bleached Coral',
                'kategoria_id' => 46,
                'marka_id' => 4,
                'nem' => 'gyerek',
                'anyag' => 'bor/velúr',
                'kepUrl' => 'Jordan1BleachedCoral.jpg',
                'ar' => 72000,
                'elerheto' => true,
                'leiras' => 'Szürke velúr, fehér bőr és finom korall árnyalatok keveréke.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Retro High Court Purple White',
                'kategoria_id' => 47,
                'marka_id' => 4,
                'nem' => 'gyerek',
                'anyag' => 'bor',
                'kepUrl' => 'Jordan1CourtPurple.jpg',
                'ar' => 88000,
                'elerheto' => true,
                'leiras' => 'Királyi lila és fehér kontrasztja klasszikus magas szárú kivitelben.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Low Shadow Toe',
                'kategoria_id' => 48,
                'marka_id' => 4,
                'nem' => 'gyerek',
                'anyag' => 'bor',
                'kepUrl' => 'Jordan1ShadowToe.jpg',
                'ar' => 58000,
                'elerheto' => true,
                'leiras' => 'Szürke, fekete és fehér panelekből álló hétköznapi kedvenc.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Retro Low OG SP Travis Scott Black Phantom',
                'kategoria_id' => 49,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'velúr',
                'kepUrl' => 'Jordan1TravisPhantom.jpg',
                'ar' => 280000,
                'elerheto' => true,
                'leiras' => 'Teljesen fekete Travis Scott kollaboráció kontrasztos fehér varrással.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Retro Low OG SP Travis Scott Velvet Brown',
                'kategoria_id' => 50,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'velúr',
                'kepUrl' => 'Jordan1TravisVelvet.jpg',
                'ar' => 240000,
                'elerheto' => true,
                'leiras' => 'Sötétbarna bársonyos hatású velúr felsőrész fordított pipával.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Retro Low OG SP Travis Scott Reverse Mocha',
                'kategoria_id' => 51,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'bor/velúr',
                'kepUrl' => 'Jordan1TravisMocha.jpg',
                'ar' => 450000,
                'elerheto' => true,
                'leiras' => 'A legnépszerűbb Travis Scott színállás: barna velúr és krémfehér bőr.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 1 Low Triple White Tumbled Leather',
                'kategoria_id' => 52,
                'marka_id' => 4,
                'nem' => 'unisex',
                'anyag' => 'bor',
                'kepUrl' => 'Jordan1TripleWhite.jpg',
                'ar' => 48000,
                'elerheto' => true,
                'leiras' => 'Teljesen fehér, texturált bőrből készült letisztult alapmodell.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 11 Retro DMP Gratitude',
                'kategoria_id' => 53,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'lakkbor/bor',
                'kepUrl' => 'Jordan11DMP.jpg',
                'ar' => 105000,
                'elerheto' => true,
                'leiras' => 'A hálát és a győzelmet szimbolizáló lakkbőr borítású ünnepi kiadás.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 11 Retro Gamma Blue (2025)',
                'kategoria_id' => 54,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'lakkbor/szintetikus',
                'kepUrl' => 'Jordan11Gamma.jpg',
                'ar' => 125000,
                'elerheto' => true,
                'leiras' => 'Fekete lakkbőr kék akcentusokkal, a Jordan 11 sorozat egyik legkeresettebb tagja.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Jordan 11 Retro Pearl',
                'kategoria_id' => 55,
                'marka_id' => 4,
                'nem' => 'no',
                'anyag' => 'lakkbor',
                'kepUrl' => 'Jordan11Pearl.jpg',
                'ar' => 95000,
                'elerheto' => true,
                'leiras' => 'Gyöngyházfényű részletekkel ellátott elegáns, női Jordan 11-es.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Maison Mihara Yasuhiro Peterson OG Sole Canvas Low Black',
                'kategoria_id' => 56,
                'marka_id' => 22,
                'nem' => 'unisex',
                'anyag' => 'vászon',
                'kepUrl' => 'MiharaPeterson.jpg',
                'ar' => 140000,
                'elerheto' => true,
                'leiras' => 'Különleges, "olvadt" talpszerkezettel rendelkező avantgárd japán design.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Nike Air Force 1 Low Supreme Black',
                'kategoria_id' => 57,
                'marka_id' => 1,
                'nem' => 'unisex',
                'anyag' => 'bor',
                'kepUrl' => 'AF1SupremeBlack.jpg',
                'ar' => 75000,
                'elerheto' => true,
                'leiras' => 'Minimalista fekete AF1 a híres piros Supreme Box logóval.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Air Jordan 4 Retro Military Black',
                'kategoria_id' => 58,
                'marka_id' => 4,
                'nem' => 'unisex',
                'anyag' => 'bor/velúr',
                'kepUrl' => 'Jordan4MilitaryBlack.jpg',
                'ar' => 160000,
                'elerheto' => true,
                'leiras' => 'Fehér, szürke és fekete színek tökéletes harmóniája minden szetthez.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Nike Dunk Low Grey Fog',
                'kategoria_id' => 59,
                'marka_id' => 1,
                'nem' => 'unisex',
                'anyag' => 'bor',
                'kepUrl' => 'DunkGreyFog.jpg',
                'ar' => 55000,
                'elerheto' => true,
                'leiras' => 'Népszerű kéttónusú szürke-fehér Dunk az egyszerűség kedvelőinek.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Adidas Campus 00s Grey White',
                'kategoria_id' => 60,
                'marka_id' => 2,
                'nem' => 'unisex',
                'anyag' => 'velúr',
                'kepUrl' => 'AdidasCampusGrey.jpg',
                'ar' => 42000,
                'elerheto' => true,
                'leiras' => 'Vastag nyelv és retró gördeszkás stílus a kényelem jegyében.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Yeezy Slide Onyx',
                'kategoria_id' => 61,
                'marka_id' => 61,
                'nem' => 'unisex',
                'anyag' => 'EVA hab',
                'kepUrl' => 'YeezySlideOnyx.jpg',
                'ar' => 45000,
                'elerheto' => true,
                'leiras' => 'Extrém kényelmes, futurisztikus megjelenésű fekete papucs.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'NIKE AIR MAX PLUS Triple Black',
                'kategoria_id' => 62,
                'marka_id' => 1,
                'nem' => 'gyerek',
                'anyag' => 'szintetikus/textil',
                'kepUrl' => 'AirMaxPlusBlack.jpg',
                'ar' => 69990,
                'elerheto' => true,
                'leiras' => 'Agresszív vonalvezetés és látható Air egységek teljesen feketében.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Timberland 6" Premium Waterproof Boot Wheat',
                'kategoria_id' => 63,
                'marka_id' => 10,
                'nem' => 'unisex',
                'anyag' => 'nubuk',
                'kepUrl' => 'TimberlandWheat.jpg',
                'ar' => 84990,
                'elerheto' => true,
                'leiras' => 'Vízálló, strapabíró és ikonikus sárga bakancs a téli napokra.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Crocs x Cars Mater',
                'kategoria_id' => 64,
                'marka_id' => 64,
                'nem' => 'unisex',
                'anyag' => 'Croslite',
                'kepUrl' => 'CrocsMater.jpg',
                'ar' => 35000,
                'elerheto' => true,
                'leiras' => 'Különleges Verda kollaboráció a mókás Matuka karakterével.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Air Jordan 1 Retro Low OG SP Travis Scott Canary',
                'kategoria_id' => 65,
                'marka_id' => 4,
                'nem' => 'no',
                'anyag' => 'bor',
                'kepUrl' => 'Jordan1TravisCanary.jpg',
                'ar' => 190000,
                'elerheto' => true,
                'leiras' => 'Élénk sárga-kék színállás Travis Scott jellegzetes stíluselemeivel.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nev' => 'Air Jordan 1 Retro High OG Bred Patent',
                'kategoria_id' => 66,
                'marka_id' => 4,
                'nem' => 'ferfi',
                'anyag' => 'lakkbor',
                'kepUrl' => 'Jordan1BredPatent.jpg',
                'ar' => 110000,
                'elerheto' => true,
                'leiras' => 'A klasszikus piros-fekete színállás csillogó lakkbőr kivitelben.',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
